ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "recursion-visualizer"
  site-url: "https://ez2rok.github.io/recursion-visualizer"
  description: "Visualize recursive functions with beautiful animations"
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/ez2rok/recursion-visualizer"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/ez2rok/recursion-visualizer"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
