# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/recursion-visualizer',
                'doc_host': 'https://ez2rok.github.io',
                'git_url': 'https://github.com/ez2rok/recursion-visualizer',
                'lib_path': 'recursion_visualizer'},
  'syms': {'recursion_visualizer.core': {'recursion_visualizer.core.foo': ('core.html#foo', 'recursion_visualizer/core.py')}}}