name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: sudo apt-get update; sudo apt-get install graphviz-dev; pip install pygraphviz;
      - name: deploy
        uses: fastai/workflows/quarto-ghp@master


        
