name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: sudo apt-get update; sudo apt-get install libgraphviz-dev
      - name: CI
        uses: fastai/workflows/quarto-ghp@master
