name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: install
        run: sudo apt-get update; sudo apt-get install graphviz-dev
      - name: test
        uses: fastai/workflows/nbdev-ci@master
