name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: install
        run: apt-get update; apt-get install libgraphviz-dev
      - name: test
        uses: fastai/workflows/nbdev-ci@master
